@include('layouts.common.website._tpl_start')
@include('layouts.common.website._header')
@yield('content')
@include('layouts.common.website._ads')
@include('layouts.common.website._newslatters')
@include('layouts.common.website._footer')
@include('layouts.common.website._tpl_end')